name: Web E2E Tests

on:
  workflow_dispatch

jobs:
  web-tests:

    runs-on: ubuntu-latest

    steps:

     #clone do projeto para maquina     
     - uses: actions/checkout@v4

     # conferir a versão do node instalada
     - name: Node version
       run: node --version

     - name: Instalando dependencias  
       run: npm install

     - name: Executando os testes
       run: npx cypress run 

     - uses: actions/upload-artifact@v4
       if: ${{!cancelled()}}
       with:
        name: relatorios
        path: |
          cypress/reports
          cypress/screenshots
          cypress/videos



       
     
