name: Web E2E Tests

on:
  workflow_dispatch:

jobs:
  web-tests:
    runs-on: ubuntu-latest

    steps:
      # Clone do projeto
      - uses: actions/checkout@v4

      # Conferir a versão do Node
      - name: Node version
        run: node --version

      # Instalar dependências
      - name: Instalando dependências
        run: npm install

      # Executar os testes Cypress
      - name: Executando os testes
        run: npx cypress run

      # Upload dos relatórios e evidências
      - name: Upload dos relatórios
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: relatorios
          path: |
            cypress/reports
            cypress/screenshots
            cypress/videos
